name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - vipul
validations:
  required: true
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 3.9.4
        - 5.8
        - 6.1
    validations:
      required: true
  - type: dropdown
    id: edition
    attributes:
      label: Edition
      multiple: true
      options:
        - Xpress
        - Pro
        - Enterprise
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      multiple: false
      options:
        - KC
        - Common
        - Playout
        - Designer
        - Vset
        - Sting Server
        - R2D
        - Sting Client
        - Databuzz
        - Hivemanager
        - MOS
    validations:
      required: true
  - type: dropdown
    id: customername
    attributes:
      label: Customer Name
      multiple: true
      options:
        - DD
        - ABP
  - type: checkboxes
    id: verifiedqa
    attributes:
      label: VerifiedByQA 
      options:
        - label: Verified By QA
          required: false
  - type: checkboxes
    id: customerreorted
    attributes:
      label: CustomerReported
      options:
        - label: Customer Reported
          required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      multiple: false
      options:
        - Low
        - Normal
        - High
        - Critical
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: true
      options:
        - Low
        - Normal
        - High
        - Critical        
  - type: input
    id: reportedbuild
    attributes:
      label: Reported Build 
    validations:
      required: false        
  - type: input
    id: completedbuild
    attributes:
      label: Completed Build 
    validations:
      required: false
      

